site_name: Computational Biology Core - Brown University
site_author: Eric Salomaki
repo_url: https://github.com/compbiocore/covid19_analysis
site_description: Documentation for running covid analysis pipeline
site_url: https://compbiocore.github.io/
google_analytics: [ 'UA-115983496-2', 'compbiocore.github.io' ]

theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate
  palette:
    primary: 'cyan'
    accent: 'deep orange'
  logo: assets/cbc-logo.svg

extra_css:
  - styles/dark_mode.css
  - docs/assets/adm.css
  - https://use.fontawesome.com/releases/v5.8.0/css/all.css
markdown_extensions:
  - extra
  - tables
  - admonition
  - codehilite
  - footnotes
  - pymdownx.superfences
  - pymdownx.details

nav:
  - Home: index.md
  - Command Options: command_description.md
  - Tutorials:
      - Download All genomes: tutorials/download_all.md
      - Download a specific list of Genomes: tutorials/download_list.md
      - Exclude one genome from a set: tutorials/exclude_one.md
