library(tidyverse)

setwd("/gpfs/data/ris3/dev/20230312/3_results/20230313/")
ri <- read_csv("qc-passed.csv") %>%
  select(date, pangolin.lineage, cdc.classification) %>%
  arrange(date)

top <- group_by(ri, pangolin.lineage) %>% tally() %>% arrange(desc(n))
write_csv(top, "top-lineages.csv")

ri <- mutate(ri,
             step=1,
             voc=as.factor(case_when(pangolin.lineage == "Q.1" ~ "Alpha lineage (VBM)",
                                     pangolin.lineage == "Q.4" ~ "Alpha lineage (VBM)",
                                     pangolin.lineage == "Q.5" ~ "Alpha lineage (VBM)",
                                     pangolin.lineage == "Q.6" ~ "Alpha lineage (VBM)",
                                     pangolin.lineage == "Q.7" ~ "Alpha lineage (VBM)",
                                     pangolin.lineage == "B.1.1.7" ~ "Alpha lineage (VBM)",
                                     pangolin.lineage == "B.1.351" ~ "Beta lineage (VBM)",
                                     pangolin.lineage == "B.1.351.2" ~ "Beta lineage (VBM)",
                                     pangolin.lineage == "B.1.351.3" ~ "Beta lineage (VBM)",
                                     pangolin.lineage == "B.1.427" ~ "Epsilon lineage (VBM)",
                                     pangolin.lineage == "B.1.429" ~ "Epsilon lineage (VBM)",
                                     pangolin.lineage == "B.1.525" ~ "Eta lineage (VBM)",
                                     pangolin.lineage == "B.1.526" ~ "Iota lineage (VBM)",
                                     pangolin.lineage == "B.1.617.1" ~ "Kappa lineage (VBM)",
                                     pangolin.lineage == "B.1.621" ~ "Mu lineage (VBM)",
                                     pangolin.lineage == "B.1.621.1" ~ "Mu lineage (VBM)",
                                     pangolin.lineage == "B.1.621.2" ~ "Mu lineage (VBM)",
                                     pangolin.lineage == "BB.2" ~ "Mu lineage (VBM)",
                                     pangolin.lineage == "P.1" ~ "Gamma lineage (VBM)",
                                     pangolin.lineage == "P.2" ~ "Zeta lineage (VBM)",
                                     pangolin.lineage == "P.3" ~ "Theta lineage (VBM)",
                                     pangolin.lineage == "AY.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.10" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.100" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.103" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.105" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.107" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.11" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.110" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.113" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.114" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.116" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.116.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.117" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.118" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.119" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.119.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.119.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.120" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.120.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.121" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.122.6" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.124" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.124.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.124.1.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.125" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.126" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.127" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.127.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.129" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.13" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.133" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.15" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.16" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.17" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.20" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.22" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.23" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.23.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.25" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.25.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.25.1.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.25.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.26" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.27" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.3.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.3.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.3.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.3.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.33" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.33.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.34" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.34.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.34.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.35" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.36" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.37" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.39" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.39.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.39.1.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.39.1.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.39.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.10" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.11" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.13" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.15" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.2.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.2.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.2.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.2.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.6" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.7" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.8" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.4.9" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.40" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.41" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.42" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.42.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.6" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.8" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.43.9" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.44" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.46" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.46.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.46.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.46.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.47" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.48" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.49" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.5.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.5.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.5.3" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.5.4" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.5.5" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.51" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.52" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.53" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.54" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.56" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.6" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.60" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.62" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.64" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.65" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.67" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.68" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.7" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.7.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.7.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.70" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.71" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.72" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.74" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.75" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.77" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.8" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.81" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.87" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.9" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.9.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.90" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.91" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.94" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.98" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.98.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "AY.98.1.1" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "B.1.617.2" ~ "Delta lineage (VBM)",
                                     pangolin.lineage == "B.1.1.529" ~ "B.1.1.529 lineage (VOC)",
                                     pangolin.lineage == "BA.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.10" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.11" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.12" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.13" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.14" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.15" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.16" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.17" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.18" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.2" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.3" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.4" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.5" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.6" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.7" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.8" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.1.9" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.10" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.12" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.13" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.13.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.14" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.14.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.14.2" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.15" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.15.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.15.2" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.15.3" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.16" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.16.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.16.2" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.17" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.17.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.17.2" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.18" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.19" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.20" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.21.1" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.23" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.3" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.4" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.5" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.8" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.1.9" ~ "BA.1 lineage (VOC)",
                                     pangolin.lineage == "BA.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.10" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.10.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.10.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.10.3" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.10.4" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.11" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.12" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.12.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.12.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.13" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.13.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.14" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.15" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.17" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.18" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.19" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.2.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.20" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.21" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.22" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.23" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.23.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.24" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.25" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.25.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.26" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.27" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.28" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.29" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.10" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.11" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.12" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.13" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.14" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.15" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.16" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.17" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.18" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.20" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.21" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.4" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.5" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.6" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.7" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.8" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.3.9" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.30" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.31" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.31.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.32" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.33" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.34" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.35" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.36" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.37" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.38" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.38.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.38.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.38.3" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.39" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.4" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.40" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.40.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.41" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.42" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.43" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.44" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.45" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.46" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.47" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.48" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.49" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.5" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.50" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.51" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.52" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.53" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.54" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.55" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.56" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.57" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.58" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.59" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.6" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.60" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.61" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.62" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.63" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.64" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.66" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.67" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.68" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.7" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.70" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.71" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.72" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.73" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.74" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.75" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.75.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.75.3" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.75.4" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.75.5" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.75.9" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.76" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.76.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.77" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.78" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.79" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.79.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.8" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.80" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.81" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.82" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.1" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.2" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.3" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.4" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.5" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.6" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.2.9.7" ~ "BA.2 lineage (VOC)",
                                     pangolin.lineage == "BA.3" ~ "BA.3 lineage (VOC)",
                                     pangolin.lineage == "BA.3.1" ~ "BA.3 lineage (VOC)",
                                     pangolin.lineage == "BA.4" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.1" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.10" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.2" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.3" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.4" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.5" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.6" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.8" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.1.9" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.2" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.3" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.4" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.5" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.6" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.6.1" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.6.2" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.6.3" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.6.4" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.6.5" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.4.7" ~ "BA.4 lineage (VOC)",
                                     pangolin.lineage == "BA.5" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.10" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.11" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.12" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.15" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.18" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.2" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.20" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.21" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.22" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.23" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.24" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.25" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.27" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.28" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.29" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.3" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.30" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.31" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.32" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.4" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.5" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.6" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.7" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.8" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.1.9" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.10" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.10.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.11" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.11" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.12" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.13" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.14" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.16" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.18" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.19" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.2" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.20" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.21" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.22" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.23" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.24" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.25" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.26" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.27" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.28" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.29" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.3" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.31" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.32" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.33" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.34" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.35" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.37" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.4" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.42" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.43" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.44" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.45" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.47" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.48" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.49" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.6" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.7" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.8" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.2.9" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.3" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.3.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.3.2" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.3.3" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.3.4" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.3.5" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.5" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.5.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.5.2" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.5.3" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.6" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.6.1" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.6.2" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.6.3" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.6.4" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.8" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BA.5.9" ~ "BA.5 lineage (VOC)",
                                     pangolin.lineage == "BC.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BC.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BD.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.2.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.4.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.4.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.4.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.1.4.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.4.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.4.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.4.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BE.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.10.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.11" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.11.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.11.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.11.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.11.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.11.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.12" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.13" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.14" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.15" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.16" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.17" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.19" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.21" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.22" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.25" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.26" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.27" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.28" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.29" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.30" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.31" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.31.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.32" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.34" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.5.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.11" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.12" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.13" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.13.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.13.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.14" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.14.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.4.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.4.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.5.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.7.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BF.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BG.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BG.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BG.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BG.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BG.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BH.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BJ.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BK.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.1.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BL.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BM.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BM.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BM.4.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BM.4.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BM.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.11" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.2.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.3.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.4.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.1.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.2.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.3.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BN.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BP.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.11" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.13" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.14" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.15" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.16" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.17" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.18" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.19" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.20" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.21" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.22" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.23" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.24" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.25" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.26" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.27" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.28" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.30" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.31" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.32" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.35" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.37" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.38" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.39" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.40" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.41" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.42" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.43" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.45" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.47" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.48" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.49" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.1.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.10.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.11" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.11.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.12" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.13" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.13.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.14" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.15" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.16" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.17" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.18" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.2.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.20" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.21" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.23" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.24" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.25" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.25.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.26" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.26.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.8.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.1.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BQ.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.2.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BR.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BT.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BT.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BU.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BU.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BU.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BV.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BW.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BW.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "BZ.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.3.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CA.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CC.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CD.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CD.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CF.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.7" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.1.1.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CH.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CK.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CK.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CK.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CK.2.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CK.2.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CK.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.10" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.11" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.12" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.4.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.5" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.5.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.6.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.8" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.8.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CM.9" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CN.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CN.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CP.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CP.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CP.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CP.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CP.4" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CP.6" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CQ.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CQ.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CQ.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CR.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CR.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CR.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CR.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CS.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "CY.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DB.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DC.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DE.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DE.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DF.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DF.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DH.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DJ.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DJ.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DJ.1.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DJ.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DJ.1.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DK.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DL.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DN.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DN.1.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DN.1.1.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DQ.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DR.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DS.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DS.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DT.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DU.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DV.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DV.2" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DV.3" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DW.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "DY.1" ~ "Other Omicron lineage (VOC)",
                                     pangolin.lineage == "XAA" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAB" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAE" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAG" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAJ" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAK" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAL" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAM" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAN" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAQ" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAS" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAU" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAV" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAY" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAY.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XAZ" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.10" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.11" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.3" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.4" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.4.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.5" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.5.2" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.5.3" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.6" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.7" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.1.9" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.2" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.2.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.2.2" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.2.3" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.3" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.3.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.3.2" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.3.3" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.4" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.6" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBB.6.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBC" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBC.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBC.1.1" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBD" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBE" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBF" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBJ" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBM" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XBP" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XD" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XE" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XF" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XG" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XH" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XL" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XN" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XQ" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XS" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XV" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XW" ~ "Recombinant Omicron lineage (VOC)",
                                     pangolin.lineage == "XZ" ~ "Recombinant Omicron lineage (VOC)",
                                     TRUE                          ~ "Other")))

nseq <- nrow(ri)
earliest <- min(ri$date)
latest <- max(ri$date)

ri <- group_by(ri, date, voc) %>%
  summarise(step=sum(step)) %>%
  ungroup() %>%
  group_by(voc) %>%
  mutate(Cumulative=cumsum(step)) %>%
  ungroup()

# Summarize by week
ri <- mutate(ri, week=lubridate::floor_date(date, unit="week")) %>%
  group_by(week, voc) %>%
  summarise(Cumulative=max(Cumulative)) %>%
  ungroup() %>%
  pivot_wider(names_from=voc, values_from=Cumulative)

print(ri)

ri <- tibble(week=seq.Date(from=lubridate::floor_date(earliest, unit="week"), to=lubridate::floor_date(latest, unit="week"), by="week")) %>% 
  left_join(ri, on="week") %>%
  fill(everything()) %>%
  replace(is.na(.), 0)

print(ri)


# good to here
ri <- ri %>%
  pivot_longer(!week, names_to="voc", values_to="Cumulative") %>%
  mutate(voc=factor(voc, levels=c("Alpha lineage (VBM)", "Beta lineage (VBM)", "Epsilon lineage (VBM)", "Eta lineage (VBM)", "Iota lineage (VBM)", "Kappa lineage (VBM)", "Mu lineage (VBM)", "Gamma lineage (VBM)", "Zeta lineage (VBM)", "Theta lineage (VBM)", "Delta lineage (VBM)", "B.1.1.529 lineage (VOC)", "BA.1 lineage (VOC)", "BA.2 lineage (VOC)", "BA.3 lineage (VOC)", "BA.4 lineage (VOC)", "BA.5 lineage (VOC)", "Other Omicron lineage (VOC)", "Recombinant Omicron lineage (VOC)", "Other")))

print(ri)

g <- ggplot(data=ri) +
  geom_area(aes(x=week, y=Cumulative, fill=voc)) +
  geom_hline(yintercept=nseq, linetype="dashed", color="black", size=0.25) +
  geom_text(
    data=data.frame(x=earliest, y=c(1.02*nseq), label=c(paste(scales::comma(nseq), "RI SARS-CoV-2 sequences as of", strftime(latest, format="%B %-m, %Y")))),
    aes(x=x, y=y, label=label, vjust=0, hjust=0),
    size=2.5
  ) +
  labs(
    x="Date of Sample",
    y="Cumulative Number of Sequences",
    fill="Lineage"
  ) +
  scale_x_date(
    breaks=waiver(),
    date_breaks="month",
    labels=waiver(),
    date_labels="%b %Y"
  ) +
  scale_y_continuous(breaks=seq(0, nseq, 500), position="right") +
  scale_fill_manual(
    values=c("BA.1 lineage (VOC)" = "#B22222",
             "B.1.1.529 lineage (VOC)"="#FF3030",
             "BA.2 lineage (VOC)"="#EE2C2C",
             "BA.3 lineage (VOC)"="#CD2626",
             "BA.4 lineage (VOC)"="#8B1A1A",
             "BA.5 lineage (VOC)"="#FF4040",
             "Other Omicron lineage (VOC)" = "#EE0000",
             "Recombinant Omicron lineage (VOC)" = "#FF0000",
             "Alpha lineage (VBM)" = "#7D26CD",
             "Beta lineage (VBM)" = "#FFBBFF",
             "Epsilon lineage (VBM)" = "#BBFFFF",
             "Eta lineage (VBM)" = "#FFDAB9",
             "Iota lineage (VBM)" = "#EECBAD",
             "Kappa lineage (VBM)" = "#FF83FA",
             "Mu lineage (VBM)" = "#FFE4E1",
             "Gamma lineage (VBM)" = "#C0FF3E",
             "Zeta lineage (VBM)" = "#5D478B",
             "Theta lineage (VBM)" = "#B0E2FF",
             "Delta lineage (VBM)" = "#FFFF00",
             "Other"="gray"
    )
  ) +
  theme_classic() +
  theme(
    title=element_text(size=9),
    legend.position=c(0, 0.5),
    legend.justification=c("left", "center"),
    legend.title=element_text(size=9),
    legend.text=element_text(size=8),
    legend.key.size=unit(0.1, "in"),
    axis.line=element_blank(),
    axis.ticks.x=element_line(size=0.25),
    axis.ticks.y=element_blank(),
    axis.text.x=element_text(size=8, color="black", angle=90, hjust=1, vjust=0.5),
    axis.text.y=element_text(size=8, color="black"),
    panel.grid.major.y=element_line(color="gray", size=0.1)
  )

pdf(file="Fig_Cumulative_lineages_sequenced_in_RI.pdf", width=10, height=10)
print(g)
dev.off()